name: applepsi_tasarim
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.4 <4.0.0'  # Dart SDK sürüm aralığı

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^2.24.0  # Firebase Core'un en son sürümü
  firebase_auth: ^4.18.0  # Firebase Auth'un en son sürümü
  cloud_firestore: ^4.15.0  # Cloud Firestore'un en son sürümü
  flutter_svg: ^2.0.17
  flutter_animate: ^4.5.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0  # En son kararlı sürüm

flutter:
  uses-material-design: true